### PR TITLE
created and index.html file

### PR DESCRIPTION
**Pull request by albert-axi**
Just added a new html file. please review.

### CODE REVIEW

**Comment by AjayGhimire1998** [comment]
briliantly written html :v

**Comment by natr104** [comment]
looks good to me

**Comment by HiccupAashish** [comment]
nice

**Review by natr104 — APPROVED** [review]

**Review by AjayGhimire1998 — APPROVED** [review]

**Review by HiccupAashish — APPROVED** [review]
Done

**Pull request merged**
